language: cpp

branches:
  only:
    - master

matrix:
  include:
  - os: linux
    dist: trusty
    env: PYTHON=3.6 CPP=11 GCC=4.8
    addons:
      apt:
        sources:
          - deadsnakes
        packages:
          - python3.6-dev
          - python3.6-venv
    install:
      - sudo curl -L -O https://cmake.org/files/v3.14/cmake-3.14.4-Linux-x86_64.tar.gz
      - sudo tar xf cmake-3.14.4-Linux-x86_64.tar.gz
      - export PATH=`pwd`/cmake-3.14.4-Linux-x86_64/bin/:$PATH

  - os: osx
    compiler: clang
    env: MACOSX_DEPLOYMENT_TARGET=10.11
  - os: windows
    env: PATH="/c/Program Files/CMake/bin/:$PATH"
    before_script:
      - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Auxiliary\Build\vcvarsall.bat" amd64

script:
- mkdir -p build
- cd build
- cmake -DCMAKE_INSTALL_PREFIX=installed -DCMAKE_BUILD_TYPE=Release ..
- cmake --build . --config Release --target install
- cpack -G ZIP
