language: cpp

branches:
  only:
    - master

matrix:
  include:
  - os: linux
    dist: trusty
    compiler: gcc
  - os: osx
    compiler: clang
    env: MACOSX_DEPLOYMENT_TARGET=10.11
  - os: windows
    env: PATH="/c/Program Files/CMake/bin/:$PATH"
 
script:
- mkdir -p build
- cd build
- cmake -DCMAKE_INSTALL_PREFIX=installed -DCMAKE_BUILD_TYPE=Release ..
- cmake --build . --config Release --target install
- cpack -G ZIP
